name: "茶话会报名"
description: "报名，在 IO 茶话会上作分享"
title: "[茶话会][请替换为参加时间例如 2024-10-25][请替换为时长例如 20 分钟] 请替换为标题"
labels: ["talk"]
body:
  - type: markdown
    attributes:
      value: |
        # 在 IO 技术茶话会预定一次分享

        IO 技术茶话会是 I/O Club 主办的系列技术分享活动。从计算机科学到世间万物，茶话会欢迎一切知识、兴趣与技能。

        有意在茶话会上作讲演的同人们请填写以下表单，并加入 qq 群 `291694149`。

        期待您的报名。

        ## 报名规则

        - 替换标题上的 参加时间，时长，标题 三项内容
        - 填写下面的表单

  - type: input
    id: author
    attributes:
      label: 署名
      description: |
        怎么称呼您？
        您的称谓可能被发布至公共领域，请注意个人隐私。
      placeholder: "姓名 | 昵称 | id ..."
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 摘要
      description: |
        请简述您的分享内容。
        您的摘要将随分享会公告一并发布。
      placeholder: |
        示例：

        从 Figma 窥见与实际开发相结合的设计入门指南
        - 初级的排版
        - 设计系统主要元素

    validations:
      required: true

  - type: checkboxes
    id: content_type
    attributes:
      label: "内容类型"
      description: |
        如果是技术类分享

        1. 一定要注意吸引力等要素，尽量避免听众睡着，可以参考首页列出的 PPT 写作/演讲技巧。
        2. 注意关注听众是否了解过您的话题，例如
          - 对于语言: go 语言有多种定义变量的方式，在你讲 go 语言的 `a := 1` 这种具有特色的语法时，使用 `var a: int32 = 1` 举例不一定合适，因为不了解 go 的人连最基本的语法都不知道
          - 对于基本术语: 初学者可能会有如下的问题
            - ip 是什么，不是域名吗？
            - 端口是什么？我从来从来没加端口？
          - 为了避免某些人的英语问题，建议说 description 之类复杂的单词时，也要跟着说一遍中文

          总之所有内容，无论是术语还是语法等等都要简化到不能简化的单位，把听众当成完全小白来看待。

        最重要的一点，不用担心做的不够好，做演讲需要不断练习积累经验 (保守估计至少需要 10 次以上才能令自己满意)

      options:
        - label: 我的分享涉及技术或计算机
    validations:
      required: true
  - type: textarea
    id: attachment
    attributes:
      label: "附件 (可选)"
      placeholder: "想写啥就写啥"
    validations:
      required: false

  - type: checkboxes
    id: pre_close_check
    attributes:
      label: "关闭 Issue 前请先确认以下内容"
      description: |
        报名人需要选择是否同意下面内容，一般同意，除非是包含敏感信息/不想公开发布的内容等等

        - 建议做 ppt (或者其他形式的东西，原则是不能照搬)，理由如下
          - 即使你的 ppt 内容有些部分例如 xxx 语法，网上已经有现成的教程。你也应该对里面的内容做筛选，以集中听众的注意力
          - 即使你的语法部分没讲多少，但是观众看到那个长长的教程网页可能就头疼了

      options:
        - label: "是否同意上传 PPT：<PR 链接>"
        - label: "是否同意上传视频：<视频链接>"
    validations:
      required: false
