name: "新任务发布"
description: '开发任务等'
title: "[任务]: "
labels: ["task"]
body:
  - type: textarea
    attributes:
      label: '如何认领'
      description: '请详细如何领取任务'
      value: |
        请直接在下方回复，我会把 issue 的 assignees 设置为你

        认领者需要遵守以下要求

        - 每两周必须在评论中更新进度，无论是学习进度还是开发进度
        - 如果**1 个月**没有任何进展, 则认定为认领失败, assign 将被取消，可以由其他人认领
        - 如遇到节假日等特殊情况，同步进度日期可以顺延

        注意事项

        - 学习也算进展，所以小白不必担心
        - 以上日期需要按照实际情况调整
        - 任务按情况可以被多人认领合作完成

    validations:
      required: false
  - type: textarea
    attributes:
      label: '需求描述'
      description: '请详细描述你的任务背景，具体需求'
      placeholder: |
        例如:

        我们希望用户在创建 issue 时要求必须填写以下内容(暂定)
        - 作者: 昵称/github_id/xxx
        - 类型: 可以是复选框, A/B/xxx/其他
        - 标题
        - 内容

    validations:
      required: true
  - type: textarea
    attributes:
      label: '实现方式'
      description: '请为任务认领者提供大致的实现思路'
      placeholder: '例如: Github 支持在 .github/ 文件夹下创建一个模板文件规定 issue 的格式'
    validations:
      required: true
  - type: textarea
    attributes:
      label: '文档资料'
      description: '请假设任务认领者为实实在在的小白，提供尽可能全面的资料，以列表形式列出'
      placeholder: |
        例如：
        - github 文档: docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
    validations:
      required: true
  - type: dropdown
    attributes:
      label: '难度'
      options:
        - 简单 (什么都不会也能学习做)
        - 中等 (需要学习多种知识，但是工作量不大，数周内可以完成)
        - 困难（工作量大，或技术方向困难）
    validations:
      required: true
  - type: textarea
    attributes:
      label: '能力要求'
      description: |
        完成任务需要学习的知识

        例如：
          - 需要能够正常访问 github, 并注册账号
          - 知道 webhook 的概念
          - 了解后端(例如 fastapi)基础使用方法
          - 对编写 qq 机器人感兴趣
      placeholder: |
        - 需要能够正常访问 github, 并注册账号
        - 需要具备一定的沟通能力，遇到困难可以主动咨询群友
        -
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: '关闭 Issue 前请确认以下内容'
      description: '请按情况勾选，一般都需要'
      options:
        - label: '需要上传代码：<PR 链接>'
        - label: '需要参加茶话会分享：<issue 链接>'
    validations:
      required: false
